[package]
name = "asmr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "0.8.4"

[dev-dependencies]
litesvm = "0.6.1"
solana-instruction = "2.2"
solana-message = "2.2"
solana-pubkey = "2.2"
solana-transaction = "2.2"
